version: '2'
services:
  products-api:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "7000:7000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://admin@postgres/products

  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: products
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432